### ISSUE TITLE
Render with multiple browsers

### ISSUE THREAD

**Issue by theblackturtle** [EdmundMartin/Sooty#1]
Hi, Can I render with multiple sites with multiple browser?. Thanks

**Comment by EdmundMartin** [comment]
Hello, 
While it is in theory possible to open multiple browsers and render pages, it's likely not needed. The library allows you to create multiple tabs which can asynchronously render pages. If you were to launch 20 tabs in one browser you would be able to render up to 20 pages at one time. 

I would only recommend looking to manage multiple browsers if you need to render a huge number of pages at once. Most use cases are covered by one browser with multiple tabs.
